# Generated by Django 3.1.3 on 2020-11-19 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('subscribed_to_daily', models.BooleanField(default=True)),
                ('people_referred_count', models.IntegerField(default=0)),
            ],
        ),
    ]
