# Generated by Django 3.1.3 on 2020-12-25 18:37

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import email_website.models
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(unique=True)),
                ('headline', models.CharField(max_length=200)),
                ('intro_html', tinymce.models.HTMLField()),
                ('market_html', tinymce.models.HTMLField()),
                ('status', models.CharField(choices=[('PG', 'В прогрессе'), ('PB', 'Опубликовано'), ('NA', 'Не одобрено к публикации')], default='PG', max_length=2)),
                ('path', models.CharField(max_length=200)),
                ('sending_time', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0), validators=[django.core.validators.MinValueValidator(datetime.datetime.now)])),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('subscribed_to_daily', models.BooleanField(default=True)),
                ('people_referred_count', models.IntegerField(default=0)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('conf_string', models.CharField(default=email_website.models.default_random_string, editable=False, max_length=15, unique=True)),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('link', models.URLField()),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_in_article', models.IntegerField()),
                ('header', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image_link', models.URLField(blank=True)),
                ('image_alt', models.CharField(blank=True, max_length=50)),
                ('caption', models.CharField(blank=True, max_length=50)),
                ('html_text', tinymce.models.HTMLField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_website.article')),
            ],
            options={
                'ordering': ['position_in_article'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='writers',
            field=models.ManyToManyField(to='email_website.Writer'),
        ),
    ]
