# Generated by Django 3.1.3 on 2020-11-20 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('headline', models.CharField(max_length=200)),
                ('intro_html', models.TextField()),
                ('status', models.CharField(choices=[('PG', 'В прогрессе'), ('PB', 'Опубликовано'), ('NA', 'Не одобрено к публикации')], default='PG', max_length=2)),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_in_article', models.IntegerField()),
                ('header', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image_link', models.URLField()),
                ('image_alt', models.CharField(max_length=50)),
                ('caption', models.CharField(blank=True, max_length=50)),
                ('html_text', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_website.article')),
            ],
            options={
                'ordering': ['position_in_article'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='writers',
            field=models.ManyToManyField(to='email_website.Writer'),
        ),
    ]
