# Generated by Django 3.1.3 on 2021-01-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='show_market',
            field=models.BooleanField(default=True),
        ),
    ]
