# Generated by Django 3.1.3 on 2021-01-01 13:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('email_website', '0002_article_show_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='market_html',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
