# Generated by Django 3.1.3 on 2020-11-24 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_website', '0003_auto_20201120_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='link',
            field=models.URLField(default='https://t.me/garrrikkotua'),
            preserve_default=False,
        ),
    ]
