# Generated by Django 3.1.3 on 2021-01-01 15:57

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('email_website', '0003_auto_20210101_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='headline',
            field=models.CharField(help_text='Название выпуска. Оно же тема письма', max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='intro_html',
            field=tinymce.models.HTMLField(help_text='Текст вступления'),
        ),
        migrations.AlterField(
            model_name='article',
            name='market_html',
            field=tinymce.models.HTMLField(blank=True, help_text='Текст про ситуацию на рынке'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(help_text='Дата выхода выпуска. Она отображается в верхнем левом углу письма', unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='show_market',
            field=models.BooleanField(default=True, help_text='Если галочка выключена, то рыночная информация не добавляется в статью, и market_html игнорируется.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('PG', 'В прогрессе'), ('PB', 'Опубликовано'), ('NA', 'Не одобрено к публикации')], default='PG', help_text='Статус выпуска. Управляется только админом.', max_length=2),
        ),
        migrations.AlterField(
            model_name='article',
            name='writers',
            field=models.ManyToManyField(help_text='Авторы выпуска', to='email_website.Writer'),
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(blank=True, help_text='Подпись под картинкой', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='header',
            field=models.CharField(help_text='Название раздела', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='html_text',
            field=tinymce.models.HTMLField(help_text='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Если картинка не загрузится, будет написан этот текст', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_link',
            field=models.URLField(blank=True, help_text='Ссылка на картинку или gif'),
        ),
        migrations.AlterField(
            model_name='post',
            name='position_in_article',
            field=models.IntegerField(help_text='Порядковыый номер статьи в выпуске'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, help_text='Название статьи', max_length=100),
        ),
    ]
