# Generated by Django 3.1.3 on 2020-11-25 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_website', '0004_writer_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(unique_for_date=True),
        ),
    ]
