# Generated by Django 3.1.3 on 2021-01-05 16:30

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('email_website', '0004_auto_20210101_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='market_data',
            field=tinymce.models.HTMLField(blank=True, help_text='Информация о рынке'),
        ),
    ]
