# Generated by Django 3.1.3 on 2020-11-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_website', '0005_auto_20201125_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(unique=True),
        ),
    ]
