# Generated by Django 3.1.3 on 2020-11-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_website', '0006_auto_20201125_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='path',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
    ]
