# Generated by Django 3.1.3 on 2020-12-05 15:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('email_website', '0007_article_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
