# Generated by Django 3.1.3 on 2020-12-08 07:35

from django.db import migrations, models
import email_website.models


class Migration(migrations.Migration):

    dependencies = [
        ('email_website', '0008_subscription_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='conf_string',
            field=models.CharField(default=email_website.models.default_random_string, editable=False, max_length=15),
        ),
        migrations.AddField(
            model_name='subscription',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
