# Generated by Django 3.1.3 on 2020-12-08 20:23

from django.db import migrations, models
import email_website.models


class Migration(migrations.Migration):

    dependencies = [
        ('email_website', '0009_auto_20201208_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='conf_string',
            field=models.CharField(default=email_website.models.default_random_string, editable=False, max_length=15, unique=True),
        ),
    ]
